name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jacobcrabill/alpine-zig:0.14.1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info

      - name: Build Linux
        run: |
          zig build -Dtarget=x86_64-linux-musl
          zig build -Dtarget=aarch64-linux-musl

      - name: Build MacOS
        run: |
          zig build -Dtarget=x86_64-macos
          zig build -Dtarget=aarch64-macos

      - name: Build Windows
        run: zig build -Dtarget=x86_64-windows

      - name: Test
        run: zig build test -Dtarget=x86_64-linux-musl
